# permissions for end users to view fcdinfoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fcdinfo-viewer-role
rules:
- apiGroups:
  - topology.corinternal.com
  resources:
  - fcdinfoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - topology.corinternal.com
  resources:
  - fcdinfoes/status
  verbs:
  - get
